namespace FYPManager.WinForms.UI.UserControls;

partial class EvaluationsControl
{
    private System.ComponentModel.IContainer components = null;
    private Panel topPanel;
    private Label lblSectionInfo;
    private TextBox txtSearch;
    private Button btnSearch;
    private Button btnAdd;
    private Button btnEdit;
    private Button btnDelete;
    private Label lblStatus;
    private ProgressBar progressBar;
    private Label lblRecordCount;
    private SplitContainer splitContainer;
    private DataGridView dgvEvaluations;
    private Panel marksPanel;
    private Label lblMarksHeading;
    private ComboBox cboGroups;
    private ComboBox cboEvaluations;
    private NumericUpDown nudObtainedMarks;
    private DateTimePicker dtpEvaluationDate;
    private Button btnRecordMarks;
    private Label lblGroupField;
    private Label lblEvaluationField;
    private Label lblMarksField;
    private Label lblDateField;
    private DataGridView dgvGroupEntries;

    protected override void Dispose(bool disposing)
    {
        if (disposing && components != null)
        {
            components.Dispose();
        }

        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        DataGridViewCellStyle dataGridViewCellStyle1 = new DataGridViewCellStyle();
        DataGridViewCellStyle dataGridViewCellStyle2 = new DataGridViewCellStyle();
        topPanel = new Panel();
        lblRecordCount = new Label();
        progressBar = new ProgressBar();
        btnDelete = new Button();
        btnEdit = new Button();
        btnAdd = new Button();
        btnSearch = new Button();
        txtSearch = new TextBox();
        lblSectionInfo = new Label();
        lblStatus = new Label();
        splitContainer = new SplitContainer();
        dgvEvaluations = new DataGridView();
        dgvGroupEntries = new DataGridView();
        marksPanel = new Panel();
        btnRecordMarks = new Button();
        dtpEvaluationDate = new DateTimePicker();
        lblDateField = new Label();
        nudObtainedMarks = new NumericUpDown();
        lblMarksField = new Label();
        cboEvaluations = new ComboBox();
        lblEvaluationField = new Label();
        cboGroups = new ComboBox();
        lblGroupField = new Label();
        lblMarksHeading = new Label();
        topPanel.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)splitContainer).BeginInit();
        splitContainer.Panel1.SuspendLayout();
        splitContainer.Panel2.SuspendLayout();
        splitContainer.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)dgvEvaluations).BeginInit();
        ((System.ComponentModel.ISupportInitialize)dgvGroupEntries).BeginInit();
        marksPanel.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)nudObtainedMarks).BeginInit();
        SuspendLayout();
        topPanel.BackColor = AppTheme.CardBackColor;
        topPanel.BorderStyle = BorderStyle.FixedSingle;
        topPanel.Controls.Add(lblRecordCount);
        topPanel.Controls.Add(progressBar);
        topPanel.Controls.Add(btnDelete);
        topPanel.Controls.Add(btnEdit);
        topPanel.Controls.Add(btnAdd);
        topPanel.Controls.Add(btnSearch);
        topPanel.Controls.Add(txtSearch);
        topPanel.Controls.Add(lblSectionInfo);
        topPanel.Dock = DockStyle.Top;
        topPanel.Padding = new Padding(18);
        topPanel.Size = new Size(960, 140);
        lblRecordCount.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        lblRecordCount.ForeColor = AppTheme.TextMuted;
        lblRecordCount.Location = new Point(817, 21);
        lblRecordCount.Size = new Size(120, 23);
        lblRecordCount.Text = "0 evaluations";
        lblRecordCount.TextAlign = ContentAlignment.MiddleRight;
        progressBar.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        progressBar.Location = new Point(826, 104);
        progressBar.MarqueeAnimationSpeed = 30;
        progressBar.Size = new Size(111, 10);
        progressBar.Style = ProgressBarStyle.Marquee;
        progressBar.Visible = false;
        btnDelete.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        btnDelete.FlatStyle = FlatStyle.Flat;
        btnDelete.ForeColor = AppTheme.DangerColor;
        btnDelete.Location = new Point(846, 64);
        btnDelete.Size = new Size(91, 30);
        btnDelete.Text = "Delete";
        btnDelete.UseVisualStyleBackColor = true;
        btnDelete.Click += btnDelete_Click;
        btnEdit.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        btnEdit.FlatStyle = FlatStyle.Flat;
        btnEdit.Location = new Point(749, 64);
        btnEdit.Size = new Size(91, 30);
        btnEdit.Text = "Edit";
        btnEdit.UseVisualStyleBackColor = true;
        btnEdit.Click += btnEdit_Click;
        btnAdd.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        btnAdd.BackColor = AppTheme.SidebarAccentColor;
        btnAdd.FlatAppearance.BorderSize = 0;
        btnAdd.FlatStyle = FlatStyle.Flat;
        btnAdd.ForeColor = Color.White;
        btnAdd.Location = new Point(652, 64);
        btnAdd.Size = new Size(91, 30);
        btnAdd.Text = "Add Evaluation";
        btnAdd.UseVisualStyleBackColor = false;
        btnAdd.Click += btnAdd_Click;
        btnSearch.FlatStyle = FlatStyle.Flat;
        btnSearch.Location = new Point(301, 69);
        btnSearch.Size = new Size(80, 26);
        btnSearch.Text = "Search";
        btnSearch.UseVisualStyleBackColor = true;
        btnSearch.Click += btnSearch_Click;
        txtSearch.Location = new Point(21, 70);
        txtSearch.PlaceholderText = "Search by evaluation name";
        txtSearch.Size = new Size(274, 23);
        lblSectionInfo.Dock = DockStyle.Top;
        lblSectionInfo.Font = new Font("Segoe UI", 10F);
        lblSectionInfo.ForeColor = AppTheme.TextMuted;
        lblSectionInfo.Location = new Point(18, 18);
        lblSectionInfo.Size = new Size(922, 40);
        lblSectionInfo.Text = "Manage evaluations and record marks against groups from one place.";
        lblStatus.Dock = DockStyle.Bottom;
        lblStatus.ForeColor = AppTheme.TextMuted;
        lblStatus.Location = new Point(0, 534);
        lblStatus.Padding = new Padding(4, 8, 4, 0);
        lblStatus.Size = new Size(960, 26);
        lblStatus.Text = "Ready";
        splitContainer.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        splitContainer.Location = new Point(0, 159);
        splitContainer.Size = new Size(960, 364);
        splitContainer.SplitterDistance = 430;
        splitContainer.Panel1.Controls.Add(dgvEvaluations);
        splitContainer.Panel2.Controls.Add(dgvGroupEntries);
        splitContainer.Panel2.Controls.Add(marksPanel);
        dgvEvaluations.AllowUserToAddRows = false;
        dgvEvaluations.AllowUserToDeleteRows = false;
        dgvEvaluations.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        dgvEvaluations.BackgroundColor = AppTheme.CardBackColor;
        dgvEvaluations.BorderStyle = BorderStyle.None;
        dataGridViewCellStyle1.Alignment = DataGridViewContentAlignment.MiddleLeft;
        dataGridViewCellStyle1.BackColor = Color.FromArgb(226, 232, 240);
        dataGridViewCellStyle1.Font = new Font("Segoe UI", 9F);
        dataGridViewCellStyle1.ForeColor = AppTheme.TextPrimary;
        dataGridViewCellStyle1.SelectionBackColor = Color.FromArgb(226, 232, 240);
        dataGridViewCellStyle1.SelectionForeColor = AppTheme.TextPrimary;
        dataGridViewCellStyle1.WrapMode = DataGridViewTriState.True;
        dgvEvaluations.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle1;
        dgvEvaluations.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
        dgvEvaluations.Dock = DockStyle.Fill;
        dgvEvaluations.EnableHeadersVisualStyles = false;
        dgvEvaluations.MultiSelect = false;
        dgvEvaluations.ReadOnly = true;
        dgvEvaluations.RowHeadersVisible = false;
        dgvEvaluations.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        dgvGroupEntries.AllowUserToAddRows = false;
        dgvGroupEntries.AllowUserToDeleteRows = false;
        dgvGroupEntries.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        dgvGroupEntries.BackgroundColor = AppTheme.CardBackColor;
        dgvGroupEntries.BorderStyle = BorderStyle.None;
        dataGridViewCellStyle2.Alignment = DataGridViewContentAlignment.MiddleLeft;
        dataGridViewCellStyle2.BackColor = Color.FromArgb(226, 232, 240);
        dataGridViewCellStyle2.Font = new Font("Segoe UI", 9F);
        dataGridViewCellStyle2.ForeColor = AppTheme.TextPrimary;
        dataGridViewCellStyle2.SelectionBackColor = Color.FromArgb(226, 232, 240);
        dataGridViewCellStyle2.SelectionForeColor = AppTheme.TextPrimary;
        dataGridViewCellStyle2.WrapMode = DataGridViewTriState.True;
        dgvGroupEntries.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
        dgvGroupEntries.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
        dgvGroupEntries.Dock = DockStyle.Fill;
        dgvGroupEntries.EnableHeadersVisualStyles = false;
        dgvGroupEntries.MultiSelect = false;
        dgvGroupEntries.ReadOnly = true;
        dgvGroupEntries.RowHeadersVisible = false;
        dgvGroupEntries.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        marksPanel.BackColor = AppTheme.CardBackColor;
        marksPanel.BorderStyle = BorderStyle.FixedSingle;
        marksPanel.Controls.Add(btnRecordMarks);
        marksPanel.Controls.Add(dtpEvaluationDate);
        marksPanel.Controls.Add(lblDateField);
        marksPanel.Controls.Add(nudObtainedMarks);
        marksPanel.Controls.Add(lblMarksField);
        marksPanel.Controls.Add(cboEvaluations);
        marksPanel.Controls.Add(lblEvaluationField);
        marksPanel.Controls.Add(cboGroups);
        marksPanel.Controls.Add(lblGroupField);
        marksPanel.Controls.Add(lblMarksHeading);
        marksPanel.Dock = DockStyle.Top;
        marksPanel.Padding = new Padding(14);
        marksPanel.Size = new Size(526, 147);
        btnRecordMarks.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        btnRecordMarks.BackColor = AppTheme.SidebarAccentColor;
        btnRecordMarks.FlatAppearance.BorderSize = 0;
        btnRecordMarks.FlatStyle = FlatStyle.Flat;
        btnRecordMarks.ForeColor = Color.White;
        btnRecordMarks.Location = new Point(406, 99);
        btnRecordMarks.Size = new Size(101, 30);
        btnRecordMarks.Text = "Record Marks";
        btnRecordMarks.UseVisualStyleBackColor = false;
        btnRecordMarks.Click += btnRecordMarks_Click;
        dtpEvaluationDate.Format = DateTimePickerFormat.Short;
        dtpEvaluationDate.Location = new Point(396, 52);
        dtpEvaluationDate.Size = new Size(111, 23);
        lblDateField.AutoSize = true;
        lblDateField.Location = new Point(396, 33);
        lblDateField.Text = "Evaluation Date";
        nudObtainedMarks.Location = new Point(281, 52);
        nudObtainedMarks.Maximum = new decimal(new int[] { 1000, 0, 0, 0 });
        nudObtainedMarks.Size = new Size(101, 23);
        lblMarksField.AutoSize = true;
        lblMarksField.Location = new Point(281, 33);
        lblMarksField.Text = "Obtained Marks";
        cboEvaluations.DropDownStyle = ComboBoxStyle.DropDownList;
        cboEvaluations.FormattingEnabled = true;
        cboEvaluations.Location = new Point(144, 52);
        cboEvaluations.Size = new Size(122, 23);
        lblEvaluationField.AutoSize = true;
        lblEvaluationField.Location = new Point(144, 33);
        lblEvaluationField.Text = "Evaluation";
        cboGroups.DropDownStyle = ComboBoxStyle.DropDownList;
        cboGroups.FormattingEnabled = true;
        cboGroups.Location = new Point(14, 52);
        cboGroups.Size = new Size(117, 23);
        cboGroups.SelectedIndexChanged += cboGroups_SelectedIndexChanged;
        lblGroupField.AutoSize = true;
        lblGroupField.Location = new Point(14, 33);
        lblGroupField.Text = "Group";
        lblMarksHeading.Dock = DockStyle.Top;
        lblMarksHeading.Font = new Font("Segoe UI Semibold", 11F, FontStyle.Bold);
        lblMarksHeading.ForeColor = AppTheme.TextPrimary;
        lblMarksHeading.Location = new Point(14, 14);
        lblMarksHeading.Size = new Size(496, 20);
        lblMarksHeading.Text = "Record Group Marks";
        AutoScaleDimensions = new SizeF(7F, 15F);
        AutoScaleMode = AutoScaleMode.Font;
        BackColor = AppTheme.ContentBackColor;
        Controls.Add(lblStatus);
        Controls.Add(splitContainer);
        Controls.Add(topPanel);
        Name = "EvaluationsControl";
        Size = new Size(960, 560);
        topPanel.ResumeLayout(false);
        topPanel.PerformLayout();
        splitContainer.Panel1.ResumeLayout(false);
        splitContainer.Panel2.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)splitContainer).EndInit();
        splitContainer.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)dgvEvaluations).EndInit();
        ((System.ComponentModel.ISupportInitialize)dgvGroupEntries).EndInit();
        marksPanel.ResumeLayout(false);
        marksPanel.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)nudObtainedMarks).EndInit();
        ResumeLayout(false);
    }
}
