namespace FYPManager.WinForms.UI.UserControls;

partial class GroupsControl
{
    private System.ComponentModel.IContainer components = null;
    private SplitContainer splitContainer;
    private Panel groupsTopPanel;
    private TextBox txtGroupSearch;
    private Button btnSearchGroups;
    private Button btnCreateGroup;
    private Button btnEditGroup;
    private Button btnDeleteGroup;
    private Label lblGroupInfo;
    private Label lblGroupCount;
    private DataGridView dgvGroups;
    private Panel membersTopPanel;
    private Label lblSelectedGroup;
    private ComboBox cboStudents;
    private ComboBox cboStatus;
    private DateTimePicker dtpAssignmentDate;
    private Button btnAddMember;
    private Button btnRemoveMember;
    private Label lblStudent;
    private Label lblStatusField;
    private Label lblAssignmentDate;
    private DataGridView dgvMembers;
    private ProgressBar progressBar;
    private Label lblStatus;
    private ComboBox cboProjects;
    private Label lblProjectField;
    private DateTimePicker dtpProjectAssignmentDate;
    private Label lblProjectAssignmentDate;
    private Button btnAssignProject;
    private Button btnRemoveProject;
    private Label lblCurrentProject;
    private Label lblProjectAssignment;

    protected override void Dispose(bool disposing)
    {
        if (disposing && components != null)
        {
            components.Dispose();
        }

        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        DataGridViewCellStyle dataGridViewCellStyle1 = new DataGridViewCellStyle();
        DataGridViewCellStyle dataGridViewCellStyle2 = new DataGridViewCellStyle();
        splitContainer = new SplitContainer();
        dgvGroups = new DataGridView();
        groupsTopPanel = new Panel();
        lblGroupCount = new Label();
        btnDeleteGroup = new Button();
        btnEditGroup = new Button();
        btnCreateGroup = new Button();
        btnSearchGroups = new Button();
        txtGroupSearch = new TextBox();
        lblGroupInfo = new Label();
        dgvMembers = new DataGridView();
        membersTopPanel = new Panel();
        btnRemoveMember = new Button();
        btnAddMember = new Button();
        dtpAssignmentDate = new DateTimePicker();
        lblAssignmentDate = new Label();
        cboStatus = new ComboBox();
        lblStatusField = new Label();
        cboStudents = new ComboBox();
        lblStudent = new Label();
        lblSelectedGroup = new Label();
        cboProjects = new ComboBox();
        lblProjectField = new Label();
        dtpProjectAssignmentDate = new DateTimePicker();
        lblProjectAssignmentDate = new Label();
        btnAssignProject = new Button();
        btnRemoveProject = new Button();
        lblCurrentProject = new Label();
        lblProjectAssignment = new Label();
        progressBar = new ProgressBar();
        lblStatus = new Label();
        ((System.ComponentModel.ISupportInitialize)splitContainer).BeginInit();
        splitContainer.Panel1.SuspendLayout();
        splitContainer.Panel2.SuspendLayout();
        splitContainer.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)dgvGroups).BeginInit();
        groupsTopPanel.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)dgvMembers).BeginInit();
        membersTopPanel.SuspendLayout();
        SuspendLayout();
        splitContainer.Dock = DockStyle.Fill;
        splitContainer.Location = new Point(0, 0);
        splitContainer.Name = "splitContainer";
        splitContainer.Panel1.Controls.Add(dgvGroups);
        splitContainer.Panel1.Controls.Add(groupsTopPanel);
        splitContainer.Panel2.Controls.Add(dgvMembers);
        splitContainer.Panel2.Controls.Add(membersTopPanel);
        splitContainer.Size = new Size(960, 534);
        splitContainer.SplitterDistance = 401;
        dgvGroups.AllowUserToAddRows = false;
        dgvGroups.AllowUserToDeleteRows = false;
        dgvGroups.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        dgvGroups.BackgroundColor = AppTheme.CardBackColor;
        dgvGroups.BorderStyle = BorderStyle.None;
        dataGridViewCellStyle1.Alignment = DataGridViewContentAlignment.MiddleLeft;
        dataGridViewCellStyle1.BackColor = Color.FromArgb(226, 232, 240);
        dataGridViewCellStyle1.Font = new Font("Segoe UI", 9F);
        dataGridViewCellStyle1.ForeColor = AppTheme.TextPrimary;
        dataGridViewCellStyle1.SelectionBackColor = Color.FromArgb(226, 232, 240);
        dataGridViewCellStyle1.SelectionForeColor = AppTheme.TextPrimary;
        dataGridViewCellStyle1.WrapMode = DataGridViewTriState.True;
        dgvGroups.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle1;
        dgvGroups.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
        dgvGroups.Dock = DockStyle.Fill;
        dgvGroups.EnableHeadersVisualStyles = false;
        dgvGroups.MultiSelect = false;
        dgvGroups.ReadOnly = true;
        dgvGroups.RowHeadersVisible = false;
        dgvGroups.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        dgvGroups.SelectionChanged += dgvGroups_SelectionChanged;
        groupsTopPanel.BackColor = AppTheme.CardBackColor;
        groupsTopPanel.BorderStyle = BorderStyle.FixedSingle;
        groupsTopPanel.Controls.Add(lblGroupCount);
        groupsTopPanel.Controls.Add(btnDeleteGroup);
        groupsTopPanel.Controls.Add(btnEditGroup);
        groupsTopPanel.Controls.Add(btnCreateGroup);
        groupsTopPanel.Controls.Add(btnSearchGroups);
        groupsTopPanel.Controls.Add(txtGroupSearch);
        groupsTopPanel.Controls.Add(lblGroupInfo);
        groupsTopPanel.Dock = DockStyle.Top;
        groupsTopPanel.Padding = new Padding(14);
        groupsTopPanel.Size = new Size(401, 128);
        lblGroupCount.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        lblGroupCount.ForeColor = AppTheme.TextMuted;
        lblGroupCount.Location = new Point(290, 18);
        lblGroupCount.Size = new Size(94, 23);
        lblGroupCount.Text = "0 groups";
        lblGroupCount.TextAlign = ContentAlignment.MiddleRight;
        btnDeleteGroup.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        btnDeleteGroup.FlatStyle = FlatStyle.Flat;
        btnDeleteGroup.ForeColor = AppTheme.DangerColor;
        btnDeleteGroup.Location = new Point(293, 84);
        btnDeleteGroup.Size = new Size(91, 28);
        btnDeleteGroup.Text = "Delete";
        btnDeleteGroup.UseVisualStyleBackColor = true;
        btnDeleteGroup.Click += btnDeleteGroup_Click;
        btnEditGroup.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        btnEditGroup.FlatStyle = FlatStyle.Flat;
        btnEditGroup.Location = new Point(196, 84);
        btnEditGroup.Size = new Size(91, 28);
        btnEditGroup.Text = "Edit";
        btnEditGroup.UseVisualStyleBackColor = true;
        btnEditGroup.Click += btnEditGroup_Click;
        btnCreateGroup.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        btnCreateGroup.BackColor = AppTheme.SidebarAccentColor;
        btnCreateGroup.FlatAppearance.BorderSize = 0;
        btnCreateGroup.FlatStyle = FlatStyle.Flat;
        btnCreateGroup.ForeColor = Color.White;
        btnCreateGroup.Location = new Point(99, 84);
        btnCreateGroup.Size = new Size(91, 28);
        btnCreateGroup.Text = "New Group";
        btnCreateGroup.UseVisualStyleBackColor = false;
        btnCreateGroup.Click += btnCreateGroup_Click;
        btnSearchGroups.FlatStyle = FlatStyle.Flat;
        btnSearchGroups.Location = new Point(291, 52);
        btnSearchGroups.Size = new Size(93, 26);
        btnSearchGroups.Text = "Search";
        btnSearchGroups.UseVisualStyleBackColor = true;
        btnSearchGroups.Click += btnSearchGroups_Click;
        txtGroupSearch.Location = new Point(14, 54);
        txtGroupSearch.PlaceholderText = "Search by ID or date";
        txtGroupSearch.Size = new Size(271, 23);
        lblGroupInfo.Dock = DockStyle.Top;
        lblGroupInfo.Font = new Font("Segoe UI", 10F);
        lblGroupInfo.ForeColor = AppTheme.TextMuted;
        lblGroupInfo.Location = new Point(14, 14);
        lblGroupInfo.Size = new Size(371, 28);
        lblGroupInfo.Text = "Create groups and review their member counts.";
        dgvMembers.AllowUserToAddRows = false;
        dgvMembers.AllowUserToDeleteRows = false;
        dgvMembers.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        dgvMembers.BackgroundColor = AppTheme.CardBackColor;
        dgvMembers.BorderStyle = BorderStyle.None;
        dataGridViewCellStyle2.Alignment = DataGridViewContentAlignment.MiddleLeft;
        dataGridViewCellStyle2.BackColor = Color.FromArgb(226, 232, 240);
        dataGridViewCellStyle2.Font = new Font("Segoe UI", 9F);
        dataGridViewCellStyle2.ForeColor = AppTheme.TextPrimary;
        dataGridViewCellStyle2.SelectionBackColor = Color.FromArgb(226, 232, 240);
        dataGridViewCellStyle2.SelectionForeColor = AppTheme.TextPrimary;
        dataGridViewCellStyle2.WrapMode = DataGridViewTriState.True;
        dgvMembers.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
        dgvMembers.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
        dgvMembers.Dock = DockStyle.Fill;
        dgvMembers.EnableHeadersVisualStyles = false;
        dgvMembers.MultiSelect = false;
        dgvMembers.ReadOnly = true;
        dgvMembers.RowHeadersVisible = false;
        dgvMembers.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        membersTopPanel.BackColor = AppTheme.CardBackColor;
        membersTopPanel.BorderStyle = BorderStyle.FixedSingle;
        membersTopPanel.Controls.Add(btnRemoveMember);
        membersTopPanel.Controls.Add(btnAddMember);
        membersTopPanel.Controls.Add(dtpAssignmentDate);
        membersTopPanel.Controls.Add(lblAssignmentDate);
        membersTopPanel.Controls.Add(cboStatus);
        membersTopPanel.Controls.Add(lblStatusField);
        membersTopPanel.Controls.Add(cboStudents);
        membersTopPanel.Controls.Add(lblStudent);
        membersTopPanel.Controls.Add(btnRemoveProject);
        membersTopPanel.Controls.Add(btnAssignProject);
        membersTopPanel.Controls.Add(dtpProjectAssignmentDate);
        membersTopPanel.Controls.Add(lblProjectAssignmentDate);
        membersTopPanel.Controls.Add(cboProjects);
        membersTopPanel.Controls.Add(lblProjectField);
        membersTopPanel.Controls.Add(lblProjectAssignment);
        membersTopPanel.Controls.Add(lblCurrentProject);
        membersTopPanel.Controls.Add(lblSelectedGroup);
        membersTopPanel.Dock = DockStyle.Top;
        membersTopPanel.Padding = new Padding(14);
        membersTopPanel.Size = new Size(555, 214);
        btnRemoveMember.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        btnRemoveMember.FlatStyle = FlatStyle.Flat;
        btnRemoveMember.ForeColor = AppTheme.DangerColor;
        btnRemoveMember.Location = new Point(443, 84);
        btnRemoveMember.Size = new Size(94, 28);
        btnRemoveMember.Text = "Remove";
        btnRemoveMember.UseVisualStyleBackColor = true;
        btnRemoveMember.Click += btnRemoveMember_Click;
        btnAddMember.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        btnAddMember.BackColor = AppTheme.SidebarAccentColor;
        btnAddMember.FlatAppearance.BorderSize = 0;
        btnAddMember.FlatStyle = FlatStyle.Flat;
        btnAddMember.ForeColor = Color.White;
        btnAddMember.Location = new Point(343, 84);
        btnAddMember.Size = new Size(94, 28);
        btnAddMember.Text = "Add Member";
        btnAddMember.UseVisualStyleBackColor = false;
        btnAddMember.Click += btnAddMember_Click;
        dtpAssignmentDate.Format = DateTimePickerFormat.Short;
        dtpAssignmentDate.Location = new Point(441, 48);
        dtpAssignmentDate.Size = new Size(96, 23);
        lblAssignmentDate.AutoSize = true;
        lblAssignmentDate.Location = new Point(441, 29);
        lblAssignmentDate.Text = "Assigned On";
        cboStatus.DropDownStyle = ComboBoxStyle.DropDownList;
        cboStatus.FormattingEnabled = true;
        cboStatus.Location = new Point(276, 48);
        cboStatus.Size = new Size(149, 23);
        lblStatusField.AutoSize = true;
        lblStatusField.Location = new Point(276, 29);
        lblStatusField.Text = "Status";
        cboStudents.DropDownStyle = ComboBoxStyle.DropDownList;
        cboStudents.FormattingEnabled = true;
        cboStudents.Location = new Point(14, 48);
        cboStudents.Size = new Size(247, 23);
        lblStudent.AutoSize = true;
        lblStudent.Location = new Point(14, 29);
        lblStudent.Text = "Student";
        lblSelectedGroup.Dock = DockStyle.Top;
        lblSelectedGroup.Font = new Font("Segoe UI Semibold", 11F, FontStyle.Bold);
        lblSelectedGroup.ForeColor = AppTheme.TextPrimary;
        lblSelectedGroup.Location = new Point(14, 14);
        lblSelectedGroup.Size = new Size(525, 20);
        lblSelectedGroup.Text = "No group selected";
        lblCurrentProject.AutoSize = true;
        lblCurrentProject.Location = new Point(14, 120);
        lblCurrentProject.Text = "Current Project";
        lblProjectAssignment.ForeColor = AppTheme.TextMuted;
        lblProjectAssignment.Location = new Point(14, 139);
        lblProjectAssignment.Size = new Size(250, 20);
        lblProjectAssignment.Text = "No project assigned";
        lblProjectField.AutoSize = true;
        lblProjectField.Location = new Point(14, 164);
        lblProjectField.Text = "Project";
        cboProjects.DropDownStyle = ComboBoxStyle.DropDownList;
        cboProjects.FormattingEnabled = true;
        cboProjects.Location = new Point(14, 183);
        cboProjects.Size = new Size(247, 23);
        lblProjectAssignmentDate.AutoSize = true;
        lblProjectAssignmentDate.Location = new Point(276, 164);
        lblProjectAssignmentDate.Text = "Assignment Date";
        dtpProjectAssignmentDate.Format = DateTimePickerFormat.Short;
        dtpProjectAssignmentDate.Location = new Point(276, 183);
        dtpProjectAssignmentDate.Size = new Size(110, 23);
        btnAssignProject.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        btnAssignProject.BackColor = AppTheme.SidebarAccentColor;
        btnAssignProject.FlatAppearance.BorderSize = 0;
        btnAssignProject.FlatStyle = FlatStyle.Flat;
        btnAssignProject.ForeColor = Color.White;
        btnAssignProject.Location = new Point(392, 179);
        btnAssignProject.Size = new Size(69, 28);
        btnAssignProject.Text = "Assign";
        btnAssignProject.UseVisualStyleBackColor = false;
        btnAssignProject.Click += btnAssignProject_Click;
        btnRemoveProject.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        btnRemoveProject.FlatStyle = FlatStyle.Flat;
        btnRemoveProject.ForeColor = AppTheme.DangerColor;
        btnRemoveProject.Location = new Point(467, 179);
        btnRemoveProject.Size = new Size(70, 28);
        btnRemoveProject.Text = "Remove";
        btnRemoveProject.UseVisualStyleBackColor = true;
        btnRemoveProject.Click += btnRemoveProject_Click;
        progressBar.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
        progressBar.Location = new Point(821, 543);
        progressBar.MarqueeAnimationSpeed = 30;
        progressBar.Size = new Size(139, 10);
        progressBar.Style = ProgressBarStyle.Marquee;
        progressBar.Visible = false;
        lblStatus.Dock = DockStyle.Bottom;
        lblStatus.ForeColor = AppTheme.TextMuted;
        lblStatus.Location = new Point(0, 534);
        lblStatus.Padding = new Padding(4, 8, 4, 0);
        lblStatus.Size = new Size(960, 26);
        lblStatus.Text = "Ready";
        AutoScaleDimensions = new SizeF(7F, 15F);
        AutoScaleMode = AutoScaleMode.Font;
        BackColor = AppTheme.ContentBackColor;
        Controls.Add(progressBar);
        Controls.Add(splitContainer);
        Controls.Add(lblStatus);
        Name = "GroupsControl";
        Size = new Size(960, 560);
        splitContainer.Panel1.ResumeLayout(false);
        splitContainer.Panel2.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)splitContainer).EndInit();
        splitContainer.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)dgvGroups).EndInit();
        groupsTopPanel.ResumeLayout(false);
        groupsTopPanel.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)dgvMembers).EndInit();
        membersTopPanel.ResumeLayout(false);
        membersTopPanel.PerformLayout();
        ResumeLayout(false);
    }
}
