namespace FYPManager.WinForms.UI.UserControls;

partial class ProjectsControl
{
    private System.ComponentModel.IContainer components = null;
    private Panel topPanel;
    private Label lblSectionInfo;
    private TextBox txtSearch;
    private Button btnSearch;
    private Button btnAdd;
    private Button btnEdit;
    private Button btnDelete;
    private Label lblStatus;
    private ProgressBar progressBar;
    private Label lblRecordCount;
    private SplitContainer splitContainer;
    private DataGridView dgvProjects;
    private Panel boardPanel;
    private Label lblSelectedProject;
    private ComboBox cboAdvisors;
    private ComboBox cboAdvisorRoles;
    private DateTimePicker dtpAdvisorAssignmentDate;
    private Button btnAssignAdvisor;
    private Button btnRemoveAdvisor;
    private Label lblAdvisorField;
    private Label lblRoleField;
    private Label lblAssignedOnField;
    private DataGridView dgvBoard;

    protected override void Dispose(bool disposing)
    {
        if (disposing && components != null)
        {
            components.Dispose();
        }

        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        DataGridViewCellStyle dataGridViewCellStyle1 = new DataGridViewCellStyle();
        DataGridViewCellStyle dataGridViewCellStyle2 = new DataGridViewCellStyle();
        topPanel = new Panel();
        lblRecordCount = new Label();
        progressBar = new ProgressBar();
        btnDelete = new Button();
        btnEdit = new Button();
        btnAdd = new Button();
        btnSearch = new Button();
        txtSearch = new TextBox();
        lblSectionInfo = new Label();
        lblStatus = new Label();
        splitContainer = new SplitContainer();
        dgvProjects = new DataGridView();
        dgvBoard = new DataGridView();
        boardPanel = new Panel();
        btnRemoveAdvisor = new Button();
        btnAssignAdvisor = new Button();
        dtpAdvisorAssignmentDate = new DateTimePicker();
        lblAssignedOnField = new Label();
        cboAdvisorRoles = new ComboBox();
        lblRoleField = new Label();
        cboAdvisors = new ComboBox();
        lblAdvisorField = new Label();
        lblSelectedProject = new Label();
        topPanel.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)splitContainer).BeginInit();
        splitContainer.Panel1.SuspendLayout();
        splitContainer.Panel2.SuspendLayout();
        splitContainer.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)dgvProjects).BeginInit();
        ((System.ComponentModel.ISupportInitialize)dgvBoard).BeginInit();
        boardPanel.SuspendLayout();
        SuspendLayout();
        topPanel.BackColor = AppTheme.CardBackColor;
        topPanel.BorderStyle = BorderStyle.FixedSingle;
        topPanel.Controls.Add(lblRecordCount);
        topPanel.Controls.Add(progressBar);
        topPanel.Controls.Add(btnDelete);
        topPanel.Controls.Add(btnEdit);
        topPanel.Controls.Add(btnAdd);
        topPanel.Controls.Add(btnSearch);
        topPanel.Controls.Add(txtSearch);
        topPanel.Controls.Add(lblSectionInfo);
        topPanel.Dock = DockStyle.Top;
        topPanel.Padding = new Padding(18);
        topPanel.Size = new Size(960, 140);
        lblRecordCount.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        lblRecordCount.ForeColor = AppTheme.TextMuted;
        lblRecordCount.Location = new Point(817, 21);
        lblRecordCount.Size = new Size(120, 23);
        lblRecordCount.Text = "0 projects";
        lblRecordCount.TextAlign = ContentAlignment.MiddleRight;
        progressBar.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        progressBar.Location = new Point(826, 104);
        progressBar.MarqueeAnimationSpeed = 30;
        progressBar.Size = new Size(111, 10);
        progressBar.Style = ProgressBarStyle.Marquee;
        progressBar.Visible = false;
        btnDelete.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        btnDelete.FlatStyle = FlatStyle.Flat;
        btnDelete.ForeColor = AppTheme.DangerColor;
        btnDelete.Location = new Point(846, 64);
        btnDelete.Size = new Size(91, 30);
        btnDelete.Text = "Delete";
        btnDelete.UseVisualStyleBackColor = true;
        btnDelete.Click += btnDelete_Click;
        btnEdit.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        btnEdit.FlatStyle = FlatStyle.Flat;
        btnEdit.Location = new Point(749, 64);
        btnEdit.Size = new Size(91, 30);
        btnEdit.Text = "Edit";
        btnEdit.UseVisualStyleBackColor = true;
        btnEdit.Click += btnEdit_Click;
        btnAdd.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        btnAdd.BackColor = AppTheme.SidebarAccentColor;
        btnAdd.FlatAppearance.BorderSize = 0;
        btnAdd.FlatStyle = FlatStyle.Flat;
        btnAdd.ForeColor = Color.White;
        btnAdd.Location = new Point(652, 64);
        btnAdd.Size = new Size(91, 30);
        btnAdd.Text = "Add Project";
        btnAdd.UseVisualStyleBackColor = false;
        btnAdd.Click += btnAdd_Click;
        btnSearch.FlatStyle = FlatStyle.Flat;
        btnSearch.Location = new Point(301, 69);
        btnSearch.Size = new Size(80, 26);
        btnSearch.Text = "Search";
        btnSearch.UseVisualStyleBackColor = true;
        btnSearch.Click += btnSearch_Click;
        txtSearch.Location = new Point(21, 70);
        txtSearch.PlaceholderText = "Search by project title or description";
        txtSearch.Size = new Size(274, 23);
        lblSectionInfo.Dock = DockStyle.Top;
        lblSectionInfo.Font = new Font("Segoe UI", 10F);
        lblSectionInfo.ForeColor = AppTheme.TextMuted;
        lblSectionInfo.Location = new Point(18, 18);
        lblSectionInfo.Size = new Size(922, 40);
        lblSectionInfo.Text = "Manage projects and assign advisory board roles from one place.";
        lblStatus.Dock = DockStyle.Bottom;
        lblStatus.ForeColor = AppTheme.TextMuted;
        lblStatus.Location = new Point(0, 534);
        lblStatus.Padding = new Padding(4, 8, 4, 0);
        lblStatus.Size = new Size(960, 26);
        lblStatus.Text = "Ready";
        splitContainer.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        splitContainer.Location = new Point(0, 159);
        splitContainer.Size = new Size(960, 364);
        splitContainer.SplitterDistance = 432;
        splitContainer.Panel1.Controls.Add(dgvProjects);
        splitContainer.Panel2.Controls.Add(dgvBoard);
        splitContainer.Panel2.Controls.Add(boardPanel);
        dgvProjects.AllowUserToAddRows = false;
        dgvProjects.AllowUserToDeleteRows = false;
        dgvProjects.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        dgvProjects.BackgroundColor = AppTheme.CardBackColor;
        dgvProjects.BorderStyle = BorderStyle.None;
        dataGridViewCellStyle1.Alignment = DataGridViewContentAlignment.MiddleLeft;
        dataGridViewCellStyle1.BackColor = Color.FromArgb(226, 232, 240);
        dataGridViewCellStyle1.Font = new Font("Segoe UI", 9F);
        dataGridViewCellStyle1.ForeColor = AppTheme.TextPrimary;
        dataGridViewCellStyle1.SelectionBackColor = Color.FromArgb(226, 232, 240);
        dataGridViewCellStyle1.SelectionForeColor = AppTheme.TextPrimary;
        dataGridViewCellStyle1.WrapMode = DataGridViewTriState.True;
        dgvProjects.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle1;
        dgvProjects.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
        dgvProjects.Dock = DockStyle.Fill;
        dgvProjects.EnableHeadersVisualStyles = false;
        dgvProjects.MultiSelect = false;
        dgvProjects.ReadOnly = true;
        dgvProjects.RowHeadersVisible = false;
        dgvProjects.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        dgvProjects.SelectionChanged += dgvProjects_SelectionChanged;
        dgvBoard.AllowUserToAddRows = false;
        dgvBoard.AllowUserToDeleteRows = false;
        dgvBoard.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        dgvBoard.BackgroundColor = AppTheme.CardBackColor;
        dgvBoard.BorderStyle = BorderStyle.None;
        dataGridViewCellStyle2.Alignment = DataGridViewContentAlignment.MiddleLeft;
        dataGridViewCellStyle2.BackColor = Color.FromArgb(226, 232, 240);
        dataGridViewCellStyle2.Font = new Font("Segoe UI", 9F);
        dataGridViewCellStyle2.ForeColor = AppTheme.TextPrimary;
        dataGridViewCellStyle2.SelectionBackColor = Color.FromArgb(226, 232, 240);
        dataGridViewCellStyle2.SelectionForeColor = AppTheme.TextPrimary;
        dataGridViewCellStyle2.WrapMode = DataGridViewTriState.True;
        dgvBoard.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
        dgvBoard.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
        dgvBoard.Dock = DockStyle.Fill;
        dgvBoard.EnableHeadersVisualStyles = false;
        dgvBoard.MultiSelect = false;
        dgvBoard.ReadOnly = true;
        dgvBoard.RowHeadersVisible = false;
        dgvBoard.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        boardPanel.BackColor = AppTheme.CardBackColor;
        boardPanel.BorderStyle = BorderStyle.FixedSingle;
        boardPanel.Controls.Add(btnRemoveAdvisor);
        boardPanel.Controls.Add(btnAssignAdvisor);
        boardPanel.Controls.Add(dtpAdvisorAssignmentDate);
        boardPanel.Controls.Add(lblAssignedOnField);
        boardPanel.Controls.Add(cboAdvisorRoles);
        boardPanel.Controls.Add(lblRoleField);
        boardPanel.Controls.Add(cboAdvisors);
        boardPanel.Controls.Add(lblAdvisorField);
        boardPanel.Controls.Add(lblSelectedProject);
        boardPanel.Dock = DockStyle.Top;
        boardPanel.Padding = new Padding(14);
        boardPanel.Size = new Size(524, 126);
        btnRemoveAdvisor.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        btnRemoveAdvisor.FlatStyle = FlatStyle.Flat;
        btnRemoveAdvisor.ForeColor = AppTheme.DangerColor;
        btnRemoveAdvisor.Location = new Point(431, 83);
        btnRemoveAdvisor.Size = new Size(74, 28);
        btnRemoveAdvisor.Text = "Remove";
        btnRemoveAdvisor.UseVisualStyleBackColor = true;
        btnRemoveAdvisor.Click += btnRemoveAdvisor_Click;
        btnAssignAdvisor.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        btnAssignAdvisor.BackColor = AppTheme.SidebarAccentColor;
        btnAssignAdvisor.FlatAppearance.BorderSize = 0;
        btnAssignAdvisor.FlatStyle = FlatStyle.Flat;
        btnAssignAdvisor.ForeColor = Color.White;
        btnAssignAdvisor.Location = new Point(352, 83);
        btnAssignAdvisor.Size = new Size(73, 28);
        btnAssignAdvisor.Text = "Assign";
        btnAssignAdvisor.UseVisualStyleBackColor = false;
        btnAssignAdvisor.Click += btnAssignAdvisor_Click;
        dtpAdvisorAssignmentDate.Format = DateTimePickerFormat.Short;
        dtpAdvisorAssignmentDate.Location = new Point(372, 51);
        dtpAdvisorAssignmentDate.Size = new Size(133, 23);
        lblAssignedOnField.AutoSize = true;
        lblAssignedOnField.Location = new Point(372, 32);
        lblAssignedOnField.Text = "Assigned On";
        cboAdvisorRoles.DropDownStyle = ComboBoxStyle.DropDownList;
        cboAdvisorRoles.FormattingEnabled = true;
        cboAdvisorRoles.Location = new Point(206, 51);
        cboAdvisorRoles.Size = new Size(150, 23);
        lblRoleField.AutoSize = true;
        lblRoleField.Location = new Point(206, 32);
        lblRoleField.Text = "Role";
        cboAdvisors.DropDownStyle = ComboBoxStyle.DropDownList;
        cboAdvisors.FormattingEnabled = true;
        cboAdvisors.Location = new Point(14, 51);
        cboAdvisors.Size = new Size(176, 23);
        lblAdvisorField.AutoSize = true;
        lblAdvisorField.Location = new Point(14, 32);
        lblAdvisorField.Text = "Advisor";
        lblSelectedProject.Dock = DockStyle.Top;
        lblSelectedProject.Font = new Font("Segoe UI Semibold", 11F, FontStyle.Bold);
        lblSelectedProject.ForeColor = AppTheme.TextPrimary;
        lblSelectedProject.Location = new Point(14, 14);
        lblSelectedProject.Size = new Size(494, 20);
        lblSelectedProject.Text = "No project selected";
        AutoScaleDimensions = new SizeF(7F, 15F);
        AutoScaleMode = AutoScaleMode.Font;
        BackColor = AppTheme.ContentBackColor;
        Controls.Add(lblStatus);
        Controls.Add(splitContainer);
        Controls.Add(topPanel);
        Name = "ProjectsControl";
        Size = new Size(960, 560);
        topPanel.ResumeLayout(false);
        topPanel.PerformLayout();
        splitContainer.Panel1.ResumeLayout(false);
        splitContainer.Panel2.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)splitContainer).EndInit();
        splitContainer.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)dgvProjects).EndInit();
        ((System.ComponentModel.ISupportInitialize)dgvBoard).EndInit();
        boardPanel.ResumeLayout(false);
        boardPanel.PerformLayout();
        ResumeLayout(false);
    }
}
