namespace FYPManager.WinForms.UI;

partial class MainForm
{
    private System.ComponentModel.IContainer components = null;
    private Panel sidebarPanel;
    private Panel headerPanel;
    private Panel contentPanel;
    private Label lblAppTitle;
    private Label lblAppSubtitle;
    private Label lblSectionTitle;
    private Button btnStudents;
    private Button btnAdvisors;
    private Button btnProjects;
    private Button btnGroups;
    private Button btnEvaluations;
    private Button btnReports;

    protected override void Dispose(bool disposing)
    {
        if (disposing && components != null)
        {
            components.Dispose();
        }

        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        sidebarPanel = new Panel();
        btnReports = new Button();
        btnEvaluations = new Button();
        btnGroups = new Button();
        btnProjects = new Button();
        btnAdvisors = new Button();
        btnStudents = new Button();
        lblAppSubtitle = new Label();
        lblAppTitle = new Label();
        headerPanel = new Panel();
        lblSectionTitle = new Label();
        contentPanel = new Panel();
        sidebarPanel.SuspendLayout();
        headerPanel.SuspendLayout();
        SuspendLayout();
        sidebarPanel.BackColor = AppTheme.SidebarBackColor;
        sidebarPanel.Controls.Add(btnReports);
        sidebarPanel.Controls.Add(btnEvaluations);
        sidebarPanel.Controls.Add(btnGroups);
        sidebarPanel.Controls.Add(btnProjects);
        sidebarPanel.Controls.Add(btnAdvisors);
        sidebarPanel.Controls.Add(btnStudents);
        sidebarPanel.Controls.Add(lblAppSubtitle);
        sidebarPanel.Controls.Add(lblAppTitle);
        sidebarPanel.Dock = DockStyle.Left;
        sidebarPanel.Location = new Point(0, 0);
        sidebarPanel.Name = "sidebarPanel";
        sidebarPanel.Padding = new Padding(20, 24, 20, 24);
        sidebarPanel.Size = new Size(230, 761);
        btnReports.Dock = DockStyle.Top;
        btnReports.FlatAppearance.BorderSize = 0;
        btnReports.FlatStyle = FlatStyle.Flat;
        btnReports.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold);
        btnReports.ForeColor = Color.White;
        btnReports.Location = new Point(20, 388);
        btnReports.Name = "btnReports";
        btnReports.Size = new Size(190, 48);
        btnReports.Text = "Reports";
        btnReports.TextAlign = ContentAlignment.MiddleLeft;
        btnReports.UseVisualStyleBackColor = true;
        btnReports.Click += btnReports_Click;
        btnEvaluations.Dock = DockStyle.Top;
        btnEvaluations.FlatAppearance.BorderSize = 0;
        btnEvaluations.FlatStyle = FlatStyle.Flat;
        btnEvaluations.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold);
        btnEvaluations.ForeColor = Color.White;
        btnEvaluations.Location = new Point(20, 340);
        btnEvaluations.Name = "btnEvaluations";
        btnEvaluations.Size = new Size(190, 48);
        btnEvaluations.Text = "Evaluations";
        btnEvaluations.TextAlign = ContentAlignment.MiddleLeft;
        btnEvaluations.UseVisualStyleBackColor = true;
        btnEvaluations.Click += btnEvaluations_Click;
        btnGroups.Dock = DockStyle.Top;
        btnGroups.FlatAppearance.BorderSize = 0;
        btnGroups.FlatStyle = FlatStyle.Flat;
        btnGroups.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold);
        btnGroups.ForeColor = Color.White;
        btnGroups.Location = new Point(20, 292);
        btnGroups.Name = "btnGroups";
        btnGroups.Size = new Size(190, 48);
        btnGroups.Text = "Groups";
        btnGroups.TextAlign = ContentAlignment.MiddleLeft;
        btnGroups.UseVisualStyleBackColor = true;
        btnGroups.Click += btnGroups_Click;
        btnProjects.Dock = DockStyle.Top;
        btnProjects.FlatAppearance.BorderSize = 0;
        btnProjects.FlatStyle = FlatStyle.Flat;
        btnProjects.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold);
        btnProjects.ForeColor = Color.White;
        btnProjects.Location = new Point(20, 244);
        btnProjects.Name = "btnProjects";
        btnProjects.Size = new Size(190, 48);
        btnProjects.Text = "Projects";
        btnProjects.TextAlign = ContentAlignment.MiddleLeft;
        btnProjects.UseVisualStyleBackColor = true;
        btnProjects.Click += btnProjects_Click;
        btnAdvisors.Dock = DockStyle.Top;
        btnAdvisors.FlatAppearance.BorderSize = 0;
        btnAdvisors.FlatStyle = FlatStyle.Flat;
        btnAdvisors.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold);
        btnAdvisors.ForeColor = Color.White;
        btnAdvisors.Location = new Point(20, 196);
        btnAdvisors.Name = "btnAdvisors";
        btnAdvisors.Size = new Size(190, 48);
        btnAdvisors.Text = "Advisors";
        btnAdvisors.TextAlign = ContentAlignment.MiddleLeft;
        btnAdvisors.UseVisualStyleBackColor = true;
        btnAdvisors.Click += btnAdvisors_Click;
        btnStudents.BackColor = AppTheme.SidebarAccentColor;
        btnStudents.Dock = DockStyle.Top;
        btnStudents.FlatAppearance.BorderSize = 0;
        btnStudents.FlatStyle = FlatStyle.Flat;
        btnStudents.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold);
        btnStudents.ForeColor = Color.White;
        btnStudents.Location = new Point(20, 148);
        btnStudents.Name = "btnStudents";
        btnStudents.Size = new Size(190, 48);
        btnStudents.Text = "Students";
        btnStudents.TextAlign = ContentAlignment.MiddleLeft;
        btnStudents.UseVisualStyleBackColor = false;
        btnStudents.Click += btnStudents_Click;
        lblAppSubtitle.Dock = DockStyle.Top;
        lblAppSubtitle.ForeColor = Color.FromArgb(148, 163, 184);
        lblAppSubtitle.Location = new Point(20, 48);
        lblAppSubtitle.Name = "lblAppSubtitle";
        lblAppSubtitle.Padding = new Padding(0, 4, 0, 24);
        lblAppSubtitle.Size = new Size(190, 100);
        lblAppSubtitle.Text = "Committee operations for final year projects";
        lblAppTitle.Dock = DockStyle.Top;
        lblAppTitle.Font = new Font("Segoe UI Semibold", 16F, FontStyle.Bold);
        lblAppTitle.ForeColor = Color.White;
        lblAppTitle.Location = new Point(20, 24);
        lblAppTitle.Name = "lblAppTitle";
        lblAppTitle.Size = new Size(190, 24);
        lblAppTitle.Text = "FYP Manager";
        headerPanel.BackColor = AppTheme.HeaderBackColor;
        headerPanel.Controls.Add(lblSectionTitle);
        headerPanel.Dock = DockStyle.Top;
        headerPanel.Location = new Point(230, 0);
        headerPanel.Name = "headerPanel";
        headerPanel.Padding = new Padding(28, 18, 28, 18);
        headerPanel.Size = new Size(1134, 82);
        lblSectionTitle.Dock = DockStyle.Fill;
        lblSectionTitle.Font = new Font("Segoe UI Semibold", 16F, FontStyle.Bold);
        lblSectionTitle.ForeColor = AppTheme.TextPrimary;
        lblSectionTitle.Location = new Point(28, 18);
        lblSectionTitle.Name = "lblSectionTitle";
        lblSectionTitle.Size = new Size(1078, 46);
        lblSectionTitle.Text = "Students";
        lblSectionTitle.TextAlign = ContentAlignment.MiddleLeft;
        contentPanel.BackColor = AppTheme.ContentBackColor;
        contentPanel.Dock = DockStyle.Fill;
        contentPanel.Location = new Point(230, 82);
        contentPanel.Name = "contentPanel";
        contentPanel.Padding = new Padding(20);
        contentPanel.Size = new Size(1134, 679);
        AutoScaleDimensions = new SizeF(7F, 15F);
        AutoScaleMode = AutoScaleMode.Font;
        BackColor = AppTheme.ContentBackColor;
        ClientSize = new Size(1364, 761);
        Controls.Add(contentPanel);
        Controls.Add(headerPanel);
        Controls.Add(sidebarPanel);
        MinimumSize = new Size(1180, 720);
        Name = "MainForm";
        StartPosition = FormStartPosition.CenterScreen;
        Text = "FYP Manager";
        sidebarPanel.ResumeLayout(false);
        headerPanel.ResumeLayout(false);
        ResumeLayout(false);
    }
}
